apiVersion: v1
kind: Service
metadata:
  name: hellostakaterapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
     k8s-app: hellostakaterapp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hellostakaterapp
    app.kubernetes.io/instance: {{ .Release.Name }}