replicaCount: 2
image:
  repository: "hello-world"
  tag: "1.0"
  pullPolicy: IfNotPresent
  
service:
  type: LoadBalancer
  port: 443
  targetPort: 5005
  timeoutSeconds: 5
  periodSeconds: 15
  protocol : TCP

application:
  name: "Stakater"
