replicaCount: 2
image:
  repository: "docker.io/myabhi04/stakater-app"
  tag: "1.0"
  pullPolicy: Always
  
service:
  type: LoadBalancer
  port: 443
  targetPort: 8080
  timeoutSeconds: 5
  periodSeconds: 15
  protocol : TCP

application:
  name: "Stakater"
